[package]
name = "clickhouse-funtime"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
clickhouse = "0.13.1"
serde = { version = "1.0.215", features = ["derive", "std"] }